### PR TITLE
Fix/bz192017

### PR DESCRIPTION
**Pull request by juergenchrist**
Various fixes and tests for bz192017.
Fix for a clang compile warning.

Open Point: Should we bump the bugfix part of the version number?

### CODE REVIEW

**Review by hfreude — APPROVED** [review]
Review done - looks very nice.

Only one concern: the __atomic_* functions are GCC only. So there should be
some kind of macro checking for gcc and echoing some #error if another compiler
is used.  I would also wrap these functions with some macro to be able to define
the macro based on the compiler used.

**Comment by juergenchrist** [comment]
> Only one concern: the __atomic_* functions are GCC only.

I tested with GCC and clang.  Both know the __atomic_* functions.  Are we worried about yet another compiler?

**Comment by juergenchrist** [comment]
We could use `CRYPTO_atomic_add` from libcrypto.  This needs a `CRYPTO_RWLOCK`, but otherwise it seems to boil down to similar code.  Will change.

**Comment by juergenchrist** [comment]
New version now uses libcrypto to handle atomicity.  Got way more complicated though...

**Review by p-steuer — APPROVED** [review]

**Review by jschmidb — COMMENTED** [review]
Good work!

**Pull request merged**
